/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BassHeader: typeof import('./src/components/Bass/BassHeader.vue')['default']
    BassLeftMenu: typeof import('./src/components/Bass/BassLeftMenu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Namespace: typeof import('./src/components/Namespace.vue')['default']
    NativeDB: typeof import('./src/components/NativeDB.vue')['default']
    NativeName: typeof import('./src/components/NativeName.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
